from tkinter import *

root = Tk()
root.title('Hotel Management')
root.geometry('500x500')
root.configure(background='red')
frm1 = Frame(bg='red')
Label(frm1,text='Hotel Management', font='arial 25 bold', padx='15', pady='5', bg='red', relief=SUNKEN, border=4).pack(padx=10, pady=10, fill=X)
frm1.pack(side=TOP, fill=X)
mainfrm = Frame()
frm2 = Frame(mainfrm)
Label(frm2,text='Roti',font='arial 10 bold',padx='5',pady='5').pack(padx=5)
tvar=IntVar()
Entry(frm2, textvariable=tvar, font='arial 10 bold').pack(padx=5, side=RIGHT)
Label(frm2,text='Roti',font='arial 10 bold',padx='5',pady='5').pack(padx=5)
tvar=IntVar()
Entry(frm2, textvariable=tvar, font='arial 10 bold').pack(padx=5, side=RIGHT)
Label(frm2,text='Roti',font='arial 10 bold',padx='5',pady='5').pack(padx=5)
tvar=IntVar()
Entry(frm2, textvariable=tvar, font='arial 10 bold').pack(padx=5, side=RIGHT)
Label(frm2,text='Roti',font='arial 10 bold',padx='5',pady='5').pack(padx=5)
tvar=IntVar()
Entry(frm2, textvariable=tvar, font='arial 10 bold').pack(padx=5, side=RIGHT)
frm2.pack(side=LEFT)
mainfrm.pack()
root.mainloop()
